development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: smessage_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: smessage_test
  pool: 5
  username:
  password:
    